GymProject/GymProject/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using GymProject.Models;
using Microsoft.AspNetCore.Authorization;

namespace GymProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            _logger.LogInformation("Executing /home/index");
            return View();
        }
        [Authorize] 
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        public IActionResult About()
        {
            return View();
        }
    }
}

GymProject/GymProject/Controllers/TrainersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using GymProject.AppLogic.Models;
using GymProject.AppLogic.Services;
using GymProject.ViewModel;
using GymProject.ViewModel.Trainers;

namespace GymProject.Controllers
{
    
    public class TrainersController : Controller
    {
        
        private readonly TrainersServices trainersServices;
        private readonly ClassServices classServices;
        public TrainersController(TrainersServices trainersServices,ClassServices classServices)
        {
            this.trainersServices = trainersServices;
            this.classServices = classServices;
        }
       


        public IActionResult Index()
        {
            try
            {
                var trainersList = trainersServices.GetAllTrainers();
                var model = new List<TrainersViewModel>();
                
                  foreach(var item in trainersList)
                  {
                    var currentItem = new TrainersViewModel();
                    var name = classServices.GetById(item.ClassId);
                      currentItem.ClassName = name.ClassName;
                      currentItem.Name = item.Name;
                      currentItem.Surname = item.Surname;
                      currentItem.Id = item.Id;
                      model.Add(currentItem);

                  }
               
                ViewData["trainers"] = model;
                return View();
            }
            catch (Exception)
            {
                return BadRequest("Invalid request received ");
            }

        }
        [HttpGet]
        public IActionResult AddTrainer()
        {
            var classList = classServices.GetAll();
            IList<String> className = new List<String>();
            foreach(var item in classList)
            {
                className.Add(item.ClassName);
            }
            ViewData["name"] = className;

            return View();
        }
        [HttpPost]
        public IActionResult AddTrainer(TrainersViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }
            var className = model.ClassName;
            var idClass = classServices.GetByName(className);
            trainersServices.AddTrainer(idClass.Id, model.Name, model.Surname);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Edit(Guid id)
        {
           try
            {
                var trainers = trainersServices.GetTrainersById(id);
                var viewModel = new TrainersViewModel
                {
                    Id = id,
                    Name = trainers.Name,
                    Surname = trainers.Surname,
                    classId = trainers.ClassId
                };
                var classList = classServices.GetAll();
                IList<String> className = new List<String>();
                foreach (var item in classList)
                {
                    className.Add(item.ClassName);
                }
                ViewData["name"] = className;
                return View(viewModel);
            }
            
            catch (Exception e)
            {
                return BadRequest(e.Message);
            }


        }
        [HttpPost]
        public IActionResult Edit(TrainersViewModel viewModel)
        {
            try
            {
                var className = viewModel.ClassName;
                var idClass = classServices.GetByName(className);

                trainersServices.Update(viewModel.Id,viewModel.Name, viewModel.Surname, idClass.Id);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                return BadRequest(e.Message);
            }
        }
        public IActionResult Delete (string Id)
        {
            try
            {
                trainersServices.Delete(Id);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                return BadRequest(e.Message);
            }
        }
    } 
}

GymProject/GymProject/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<style>
    body{
    background: black;
}
.main-p{
    width: 100%;
    height: auto;
    background: black;
}
.main-p h2{
    text-align: center;
    font-family: Tahoma, Geneva, sans-serif;
    font-size: large;
    font-weight: bold;
    color: white;
    margin-top: 20px;
    margin-left: 20px;
    margin-right: 20px;
}
    .main-p p {
        text-align: center;
        font-family: Tahoma, Geneva, sans-serif;
        font-size: larger;
        color: white;
        font-size: 1rem;
        font-weight: 300;
        margin-left: 20px;
        margin-right: 20px;
    }
.main-p span{
    color: crimson;
    font-size: 1rem;
	font-weight: 300;
}
.main-cont{
    width: 100%;
    height: auto;
    background: linear-gradient(to bottom, rgba(0,0,0,.8), rgba(0,0,0,.5)), url('/img/ff.jpg');
    background-size: cover;
    padding-bottom: 40px;
}
.main-cont image{
    margin-right: 20px;
    margin-left: 20px;
    width: 100%;
    height: 100vh;
    float: left;
}
.image{
    width: 90%;
    margin: 0 auto;
}
.image img{
    height: 250px;
    width: 300px;
    display: inline-block;
    margin-left: 20px;
    margin-top: 30px;
}
.main-cont button{
    width: 200px;
    height: 60px;
    box-shadow: 0 5px 25px rgba(0,0,0,.5);
    margin: 20px 0 0 630px;
    border-radius: 10px;
    background-color: rgba(255, 255, 255, 0.349);
}
.main-cont button:hover{
    background-color: rgb(253, 130, 155);
}
.contact{
    margin-top: 60px;
}
.contact p{
    font-size: 30px;
    text-align: center;
    font-weight: bold;
}
.contact h3{
    margin: 10px 300px 10px 300px;
    text-align: center;
    color: white;
    font-size: 20px;
    
}
</style>
    <div class="main-p">
        <h2>Top services in the largest fitness club in New York.</h2>
        <p>Step into our spacious fitness rooms and you will realize what it means to train in a modern space and be greeted by a professional team of instructors. <a>StayUp <span>To </span> Lift</a> Club offers you over 3,000 square meters of modern equipment, excellent facility and the best New York Group Fitness classes. Come and discover the <a>StayUp <span>To </span>Lift</a> experience!</p>
        <div class="main-cont">
            <h2>Personal Training!</h2>
            <p>Make the most of your time at the gym with the help of a personal trainer. From workouts created specifically for you, to the momentum you need to finish that difficult set of exercises, our instructors are always ready to help you discover your motivation and make progress toward your goals.</p>
            <div class="image">
                <img src="~/img/about1.jpg">
                <img src="~/img/about2.jpg">
                <img src="~/img/about3.jpg">
                <img src="~/img/about4.jpeg">
                <img src="~/img/about5.jpg">
                <img src="~/img/about6.jpg">
                <img src="~/img/gymgirl.png">
                <img src="~/img/work.jpg">
            </div>
           <button><a asp-controller="Trainers" asp-action="Index" class="text-white">See more details</a></button>
            <div class="contact">
                <p>Contact Info</p>
                <h3>
                    StayUpToLift has a fitness center in Craiova, where you can train in large spaces, with modern appliances and professional personal trainers. No matter what type of training you want to follow, we will surely be able to overcome your limits and reach your goals.
                </h3>
            </div>

        </div>
    </div>

GymProject/GymProject/Views/Home/Index.cshtml
@using  GymProject.Areas.Identity.Pages.Account
@{
    ViewData["Title"] = "Home Page";
}



<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>